Repository 2kkeullim/Random-Cafe, pull requests merged in 2022-08, with the labels that each got.

#2 🔀 :: (#1) 프로젝트 세팅
  RandomCafe.java
Labels: 프로젝트 설정

#6 🔀 :: (#5) Admin class 생성
  Admin.java
Labels: 기능 추가

#8 🔀 :: (#3) adminUI class 생성
  AdminUI.java
Labels: 기능 추가

#7 🔀 :: (#4) initialUI class 생성
  initialUI.java
Labels: 기능 추가

#11 🔀 :: MainUI class 생성
  MainUI.java
Labels: 기능 추가

#13 🔀 :: Open class 생성
  Open.java
Labels: 기능 추가

#15 ♻️ :: (#14) initial UI class / Open class 리팩토링
  InitialUI.java
  Open.java
Labels: 리팩토링

#16 🔀 :: (#9) AdminList class / AdminData class 생성
  AdminData.java
  AdminList.java
Labels: 기능 추가

#22 ⚡️ :: (#21) InitialUI 수정
  InitialUI.java
Labels: chore

#24 ⚡️ :: (#23) Open class if문 수정
  Open.java
Labels: chore

#28 📑 :: Member class 생성
  Member.java
Labels: 기능 추가

#31 ⚡️ :: Member class 생성자 추가
  Member.java
Labels: 리팩토링

#32 📑 :: MemberList class 생성
  MemberList.java
Labels: 기능 추가

#33 📑 :: MenuUI class 생성
  MenuUI.java
Labels: 기능 추가

#34 📑 :: AdminLogin class 생성
  AdminLogin.java
Labels: 기능 추가

#37 ⚡️ :: CategoryUI 수정
  CategoryUI.java
Labels: chore

#39 ⚡️ :: DrinkUI 수정
  DrinkUI.java
Labels: chore

#40 ⚡️ :: AdminData-AdminList class Merge
  AdminList.java
  AdminLogin.java
Labels: 기능 추가

#42 ⚰️ :: AdminData-Delete
  AdminData.java
Labels: chore

#45 ⚡️ :: InitialUI class 수정
  InitialUI.java
Labels: chore

#48 📑 :: MenuUI class 생성
  CategoryUI.java
  DrinkUI.java
  MenuUI.java
Labels: 기능 추가

#47 📑 :: Change class 생성 / Admin UI class 수정
  AdminUI.java
  Change.java
Labels: 기능 추가

#50 ♻️ :: MenuUI 리팩토링
  CategoryUI.java
  DrinkUI.java
  MenuUI.java
Labels: 리팩토링

#54 ⚡️ :: InitialUI class 수정
  AdminLogin.java
  InitialUI.java
  MenuUI.java
Labels: 리팩토링

#57 ⚡️ :: RandomCafe 수정
  RandomCafe.java
Labels: 기능 추가

#59 ⚡️ :: Open class 수정
  Open.java
Labels: chore

#61 ♻️ :: Open 과정 리팩토링
  AddChange.java
  AdminLogin.java
  AdminOpen.java
  AdminUI.java
  InitialUI.java
  Open.java
  RandomCafe.java
Labels: 리팩토링

#63 📑 :: ChangeUI class 생성
  AdminUI.java
  ChangeUI.java
Labels: 기능 추가

#64 📑 :: Coffee class 생성
  Coffee.java
Labels: 기능 추가

#66 📑 :: ReturnChange-class-생성
  ReturnChange.java
Labels: 기능 추가

#71 ⚡️ :: drink UI class 뒤로가기 구현
  CategoryUI.java
  DrinkUI.java
Labels: 기능 추가

#77 ⚡️ :: 화면 UI 수정
  Cafe.java
  InitialUI.java
  RandomCafe.java
Labels: chore

#78 📑 :: option 메소드 분리 및 Options 클래스 생성
  Ade.java
  Coffee.java
  Juice.java
  NonCoffee.java
  Options.java
  Smoothie.java
  Tea.java
Labels: 기능 추가

#81 ♻️ :: admin class 관련 UI 리팩토링
  AdminLogin.java
  AdminOpen.java
  AdminUI.java
  InitialUI.java
Labels: 리팩토링

#82 📑 :: Stamp class 생성
  Stamp.java
Labels: 기능 추가

#85 ⚡️ :: Drink class 생성 및 카테고리별 class 수정
  Ade.java
  Coffee.java
  Drink.java
  Juice.java
  NonCoffee.java
  Smoothie.java
  Tea.java
Labels: 기능 추가

#87 ♻️ :: admin 관련 UI 리팩토링
  AddChange.java
  AdminLogin.java
  AdminOpen.java
  AdminUI.java
  Cafe.java
  Cat.java
  Change.java
  ChangeUI.java
Labels: 리팩토링

#88 ⚡️ :: Stamp 기능 추가
  MemberList.java
  Stamp.java
  User.java
  UserList.java
Labels: 기능 추가

#90 📑 :: Cart class 생성 및 Category 별 class 수정
  Ade.java
  Cart.java
  CategoryUI.java
  Coffee.java
  DrinkUI.java
  Juice.java
  NonCoffee.java
  Smoothie.java
  Tea.java
Labels: 기능 추가

#92 📑 :: Coupon class 생성
  CouponUse.java
  InitialUI.java
  UserList.java
Labels: 기능 추가

#95 ⚡️ :: Thums-up
  Cat.java
Labels: chore

#96 📑 :: Receipt class 생성
  Receipt.java
Labels: 기능 추가

#97 ⚡️ :: cart class 및 카테고리 별 수정
  Ade.java
  Cart.java
  Coffee.java
  DrinkUI.java
  Juice.java
  NonCoffee.java
  Options.java
  RandomDrink.java
  Smoothie.java
  Tea.java
Labels: 기능 추가

#100 ⚡️ :: Receipt class 수정
  Receipt.java
Labels: 기능 추가

#101 📑 :: Cart class 수정, ReturnChange class 수정 , Cart class 수정
  Cart.java
  Pay.java
  ReturnChange.java
Labels: 기능 추가

#105 ⚡️ :: ReturnChange class 수정 ,Payclass 수정
  Pay.java
  ReturnChange.java
Labels: chore

#108 ⚡️ :: Receipt class 및 RandomDrink class 수정
  RandomDrink.java
  Receipt.java
Labels: 리팩토링

#109 ⚡️ :: Pay class 분리
  Pay.java
  PayCard.java
  PayCash.java
  ReturnChange.java
  UserList.java
Labels: chore

#111 ⚡️ :: admin UI class modify
  AdminUI.java
  Sales.java
Labels: 기능 추가

#114 ⚡️ :: Receipt class 수정
  Receipt.java
Labels: chore

#116 ⚡️ :: random drink class modify
  Ade.java
  Coffee.java
  Juice.java
  NonCoffee.java
  Receipt.java
  Smoothie.java
  Tea.java
Labels: chore

#117 📑 :: AddSales class 생성 및 다수 class 수정
  AddSales.java
  Ade.java
  Cart.java
  Coffee.java
  Drink.java
  Juice.java
  NonCoffee.java
  PayCard.java
  PayCash.java
  Sales.java
  Smoothie.java
  Tea.java
Labels: 기능 추가

#120 118 coupon use class modify
  CouponUse.java
  PayCard.java
  PayCash.java
  UserList.java
Labels: 기능 추가

#122 Pay class 및 다수 class 수정
  AddSales.java
  Ade.java
  Cart.java
  Coffee.java
  Drink.java
  Juice.java
  NonCoffee.java
  PayCard.java
  PayCash.java
  Receipt.java
  Sales.java
  Smoothie.java
  Tea.java
Labels: chore

#125 ⚡️ :: Pay cash ,card class 및 Sales class ,Receipt class 수정
  PayCard.java
  PayCash.java
  Receipt.java
  Sales.java
Labels: chore

#127 ⚡️ :: final modify for stamp
  CouponUse.java
  PayCard.java
  PayCash.java
  Receipt.java
  Stamp.java
  UserList.java
Labels: 기능 추가

#131 ⚡️ :: 접수번호 기능추가
  Receipt.java
Labels: 기능 추가

#135 ⚡️ :: ReturnChange class 수정
  ReturnChange.java
Labels: chore

#136 ⚡️ :: 할인가 오표기 수정 및 스탬프 적립 오류 수정
  Cart.java
  CouponUse.java
  Drink.java
  Receipt.java
  Stamp.java
  UserList.java
Labels: chore

#138 ⚡️ :: CouponUse class 사소한 수정
  CouponUse.java
Labels: chore

#140 ♻️ :: refactoring
  AddChange.java
  Admin.java
  AdminList.java
  AdminLogin.java
  AdminOpen.java
  AdminUI.java
  Cafe.java
  Cart.java
  Cat.java
  CategoryUI.java
  ChangeUI.java
  CouponUse.java
  DrinkUI.java
  InitialUI.java
  MenuUI.java
  PayCard.java
  PayCash.java
  ReturnChange.java
  Sales.java
  UserList.java
Labels: 리팩토링

#142 ♻️ :: refactoring 및 에러 수정
  CategoryUI.java
  DrinkUI.java
  InitialUI.java
Labels: 리팩토링

#144 ♻️ :: refactoring 및 코드 수정
  AddSales.java
  Ade.java
  Cart.java
  Coffee.java
  Drink.java
  Juice.java
  NonCoffee.java
  Options.java
  Receipt.java
  Smoothie.java
  Tea.java
Labels: chore, 리팩토링

#149 ♻️ :: refactoring 및 자잘한 것 수정
  Options.java
  Pay.java
  PayCard.java
  PayCash.java
  Receipt.java
  User.java
  UserList.java
Labels: chore, 리팩토링

#151 ♻️ :: refactoring
  AddSales.java
  AdminUI.java
  Receipt.java
  Sales.java
  UserList.java
Labels: 리팩토링

#153 ♻️ :: refactoring
  Cart.java
  CategoryUI.java
  Options.java
  Pay.java
  Receipt.java
  ReturnChange.java
  Sales.java
  Stamp.java
  UserList.java
Labels: 리팩토링

#155 ⚡️ :: Stamp-class-chore-modify
  Stamp.java
Labels: chore
